[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

# Optimization settings
optimizer = true
optimizer_runs = 1000  # High number of runs optimizes for deployment cost
via_ir = true            # Enable IR-based optimization
# Additional optimization settings
memory_limit = 33554432  # 32GB
evm_version = "paris"    # Target specific EVM version

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.deploy]
# More aggressive optimization for deployment
optimizer = true
optimizer_runs = 1000000
via_ir = true
# Contract size optimization flags
no_empty_blocks = true
no_unused_functions = true
no_unused_vars = true
